on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
name: "Run CI"
concurrency: 
  group: 'ci-${{ github.ref }}'
  cancel-in-progress: true
jobs:
  unit-tests:
    name: "Run unit tests"
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - name: Install dependecies
        run: pip install -r requirements.txt
      - name: Run pytest
        run: pytest -v tests/ -W ignore::DeprecationWarning
